scrape_configs:
  - job_name: "jaeger"
    scrape_interval: 5s
    metrics_path: "/metrics"
    static_configs:
      - targets: ['jaeger:14269']
  - job_name: "cadvisor"
    scrape_interval: 5s
    metrics_path: "/metrics"
    static_configs:
      - targets: ['cadvisor:8080']

rule_files:
- 'alert.rules'
